# remote_theme: daattali/beautiful-jekyll

title: 飞出国联盟

author: 飞出国联盟

navbar-links:
  联盟: "/#0"
  理念: "/#1"
  价值: "/#2"
  加入: "/#3"
  规则: "/#4"
  注意: "/#5"
  免责: "/#6"
  联系: "/contact"

title-img: /assets/img/flyabroad-logo-light.png

site-css: "/assets/css/flyabroad.css"

keywords: "飞出国联盟, 微出国论坛"

favicon: "/favicon.ico"

mobile-theme-col: "#0085A1"
navbar-col: "#05172d"
navbar-text-col: "#fff"
navbar-border-col: "#05172d"

social-network-links:
  email: "zixun@flyabroad.com.hk"
  github: flyabroad
  twitter: flyabroad
  # calendly: "attalitech/meeting"
  # youtube: "c/daattali?sub_confirmation=1"
  # patreon: DeanAttali

url-pretty: "flyabroad.org"

footer-img: "/assets/img/footer-bg.png"

google_analytics: "G-MPP7WQEQDT"

timezone: "Asia/Shanghai"
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      nav-short: true


exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
